image:
  repository: ghcr.io/tomkoren1/ai-builder-frontend
  tag: e6a4c64
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 3000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
